export const navBtns = [
  {
    id: '0',
    title: '👾 About me',
    linkTo: '/',
    level: 0,
    isActive: false,
    showChildren: false,
    children: [],
  },
  {
    id: '1',
    title: '📝 Blogs',
    linkTo: '/blogs',
    level: 0,
    isActive: false,
    showChildren: false,
    children: [
      {
        id: '0',
        title: '🖼 Frontend',
        linkTo: '/blogs/frontend',
        level: 1,
        isActive: false,
        showChildren: false,
        children: [],
      },
      {
        id: '2',
        title: '⌨️ Programming',
        linkTo: '/blogs/programming',
        level: 1,
        isActive: false,
        showChildren: false,
        children: [],
      },
    ],
  },
  {
    id: '2',
    title: '🗒 Daily logs',
    linkTo: '/daily_logs',
    level: 0,
    isActive: false,
    showChildren: false,
    children: [
      {
        id: '0',
        title: '👾 Tech',
        linkTo: '/daily_logs/tech',
        level: 1,
        isActive: false,
        showChildren: false,
        children: [],
      },
      {
        id: '1',
        title: '🍀 Life',
        linkTo: '/daily_logs/life',
        level: 1,
        isActive: false,
        showChildren: false,
        children: [],
      },
    ],
  },
  {
    id: '3',
    title: '📂 Projects',
    linkTo: '/projects',
    level: 0,
    isActive: false,
    showChildren: false,
    children: [
      {
        id: '0',
        title: '💻 Web developement',
        linkTo: '/projects/web_dev',
        level: 1,
        isActive: false,
        showChildren: false,
        children: [],
      },
      {
        id: '1',
        title: '🏆 SEO Optimization',
        linkTo: '/projects/seo',
        level: 1,
        isActive: false,
        showChildren: false,
        children: [],
      },
    ],
  },
  {
    id: '4',
    title: '🚲 My Journey',
    linkTo: '/journey',
    level: 0,
    isActive: false,
    showChildren: false,
    children: [
      {
        id: '0',
        title: '👨🏻‍💻 Developer',
        linkTo: '/journey/career',
        level: 1,
        isActive: false,
        showChildren: false,
        children: [],
      },
      {
        id: '1',
        title: '🍱 Life & Goal',
        linkTo: '/journey/life_goal',
        level: 1,
        isActive: false,
        showChildren: false,
        children: [],
      },
    ],
  },
];
